[package]
name = "libmdnsresponder"
version = "0.1.0"
edition = "2024"

[lib]
name = "mdnsresponder"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
log = "0.4.28"
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = "0.7.16"
rand = "0.9.2"
